services:
  ui:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    env_file:
      - ./src/ui/.env
    volumes:
      - ./db:/app/db
    depends_on:
      - engine

  engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./src/engine/.env
    volumes:
      - ./db:/app/db
      - ./logs:/app/src/engine/logs